[publishers]
quarto.enable = true

[jupyterlab]
runtimePackages = ["hello"]
# jupyterlabEnvArgs.extraPackages = [
#   "python-lsp-server.passthru.optional-dependencies.all"
# ]

# [jupyterlab.extensions]
# features = ["lsp", "jupytext"]

# [jupyterlab.notebookConfig.ServerApp]
# root_dir = "./docs/notebooks"
# notebook_dir = "./docs/notebooks"

[kernel.python.data-science]
enable = true
extraPackages = ["six"]
groups = ["data", "prefect"]

[kernel.bash.data-science]
enable = true

[kernel.julia.data-science]
enable = true

# [kernel.r.data-science]
#  enable = true
# extraRPackages = [
#   "dplyr",
#   "ggplot2",
#   "lubridate",
#   "readr",
#   "rmarkdown",
#   "ggrepel",
#   "tidyr"
# ]
