[tool.poetry]
name = "workflow-template-python"
version = "0.1.0"
description = ""
authors = ["guangtao <gtrunsec@hardenedlinux.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.data.dependencies]
polars = "^0.16.7"

[tool.poetry.group.prefect.dependencies]
prefect = "^2.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
