name: "CI"
on:
  push:
    branches: [main]
  pull_request:
  # schedule:
  #   - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: true
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v21
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: gtrunsec
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Doc
        run: nix develop .#doc --show-trace --refresh --command -- mkdoc

      - name: Build quarto
        run: |
          nix develop .#doc --show-trace --refresh  --command mkQuarto

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./docs/quarto/public
