
name: "DockerImages"
on:
  push:
    branches: [main]
  pull_request:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: zeek

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build workflow.desci Image
        run: |
          nix -Lv run .\#x86_64-linux.automation.containers.dev.copyToRegistry

      - name: Push the workflow.default Docker image
        run: |
          # docker run -it -v "$(pwd):/work" --entrypoint /bin/bash ghcr.io/gtrunsec/workflow-template.default:latest
          # docker push ghcr.io/gtrunsec/workflow-template.default:latest
